#!/bin/bash
#$ -N chromnitron_quick
#$ -cwd
#$ -l h_vmem=16G
#$ -l h_rt=02:00:00
#$ -l gpu=1
#$ -l os=RedHat8
#$ -hard
#$ -m ea
#$ -M stao@broadinstitute.org

# conda env
source /broad/software/free/Linux/redhat_7_x86_64/pkgs/anaconda3_2022.10/etc/profile.d/conda.sh
conda activate /broad/boxialab/sihengtao/env_all/chromnitron_gpu

export SINGULARITY_BINDPATH=/broad/boxialab/sihengtao:/broad/boxialab/sihengtao
python inference.py examples/local_config_quick.yaml
